### ISSUE TITLE
Suggestion: Command recognition

### ISSUE THREAD

**Issue by Flyken271** [MichaelJolley/number-one#6]
When someone fires a certain command (I.E. theme command), add in the chat overlay as a box that shows who fired what command with what arguments.

I.E
Flyken has changed the theme to Powershell ISE

**Comment by MichaelJolley** [comment]
@all-contributors please add @Flyken271 for ideas

@Flyken271, I'm not sure we need to show on screen who called what command with parameters because it's already in chat.  Thanks for brainstorming ideas for the bot though and I can't wait for your next one.
